<a href="https://colab.research.google.com/github/ymamathasai/DSDM-725/blob/main/Lab4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Load the data
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header=None)
test = df
print(df)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [ ]:
#replace the value 99 with NaN
test = test.replace(99, np.nan).copy()

In [ ]:
#drop column 1 as it contains jokes not ratings
test = test.drop([0], axis=1).copy()

In [ ]:
test

        1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 100 columns]

In [ ]:
max_value = test.max()
print('Maximum value in each column : ')
print(max_value)

Maximum value in each column :
1      9.37
2      9.37
3      9.37
4      9.37
5      9.37
       ...
96     9.37
97     9.37
98     9.37
99     9.37
100    9.37
Length: 100, dtype: float64

In [ ]:
min_value = test.min()
print('Minimum value in each column : ')
print(min_value)

Minimum value in each column :
1     -9.95
2     -9.95
3     -9.95
4     -9.95
5     -9.95
       ...
96    -9.95
97    -9.95
98    -9.95
99    -9.95
100   -9.95
Length: 100, dtype: float64

In [ ]:
low = test[33]
low.iloc[12215]

8.4

In [ ]:
arr = test.values
print(arr.shape)

(24983, 100)

In [ ]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)

In [ ]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [ ]:
new_arr, idx = replace(arr, 0.1)

In [ ]:
arr[idx[0][0], idx[1][0]]

0.58

In [ ]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [ ]:
n_latent_factors = 2

user_ratings = test.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [ ]:
latent_item_features

array([[0.79892669, 0.94999877],
       [0.54115569, 0.19705606],
       [0.11486135, 0.65299931],
       [0.76390644, 0.96984512],
       [0.09905274, 0.60377709],
       [0.18240345, 0.02801629],
       [0.71995068, 0.54936001],
       [0.5309503 , 0.95852404],
       [0.28137792, 0.46218927],
       [0.01645508, 0.37649403],
       [0.22823697, 0.06583411],
       [0.84631998, 0.49789502],
       [0.77007375, 0.56541907],
       [0.83570395, 0.50618235],
       [0.29943969, 0.96022327],
       [0.71583444, 0.85509261],
       [0.75559334, 0.58574402],
       [0.807272  , 0.00896314],
       [0.94084292, 0.79561723],
       [0.80115238, 0.07815771],
       [0.81170754, 0.66037579],
       [0.10079082, 0.98002707],
       [0.12886987, 0.15219016],
       [0.17225671, 0.57424953],
       [0.81446564, 0.86862362],
       [0.0240461 , 0.46447942],
       [0.51405559, 0.84059897],
       [0.30285829, 0.90224988],
       [0.95187841, 0.13805602],
       [0.05108134, 0.6403911 ],
       [0.92937488, 0.72118815],
       [0.80008638, 0.62085844],
       [0.46402521, 0.89949636],
       [0.11844545, 0.7044333 ],
       [0.31525043, 0.26114843],
       [0.63170688, 0.85940008],
       [0.33994656, 0.46088581],
       [0.15469729, 0.87720711],
       [0.34796688, 0.3583668 ],
       [0.0460089 , 0.04684446],
       [0.88515025, 0.79543936],
       [0.87287235, 0.32569786],
       [0.77244997, 0.91025073],
       [0.66795322, 0.27039389],
       [0.04314469, 0.49442633],
       [0.74171828, 0.09731979],
       [0.27204814, 0.96945526],
       [0.65583492, 0.55045764],
       [0.61297662, 0.84509865],
       [0.50418548, 0.7485043 ],
       [0.32460942, 0.51573604],
       [0.64061981, 0.09639471],
       [0.07597149, 0.1526859 ],
       [0.17678905, 0.76994751],
       [0.97397681, 0.70979061],
       [0.74568136, 0.74871385],
       [0.8377184 , 0.73120872],
       [0.74663644, 0.79968792],
       [0.06814609, 0.18797866],
       [0.08949014, 0.77884678],
       [0.31079719, 0.34435511],
       [0.29175471, 0.76479338],
       [0.1005949 , 0.9020992 ],
       [0.27917185, 0.42466628],
       [0.77674794, 0.28783373],
       [0.51768316, 0.56107146],
       [0.02247368, 0.33539514],
       [0.68734486, 0.06971772],
       [0.25282957, 0.78120589],
       [0.88314308, 0.42696584],
       [0.44654453, 0.86378303],
       [0.73340051, 0.08469157],
       [0.08141111, 0.76856234],
       [0.88211943, 0.90261831],
       [0.39503167, 0.69118449],
       [0.77096371, 0.18259994],
       [0.51973055, 0.64324381],
       [0.03908013, 0.47587763],
       [0.83419379, 0.61754342],
       [0.04635961, 0.56150007],
       [0.77501431, 0.39523162],
       [0.5980945 , 0.1321708 ],
       [0.70370257, 0.48388877],
       [0.15425869, 0.76413773],
       [0.05659736, 0.98688036],
       [0.46616065, 0.29362387],
       [0.82316259, 0.47885574],
       [0.33429329, 0.72499536],
       [0.84828361, 0.28876648],
       [0.90388285, 0.07462786],
       [0.72899582, 0.54712852],
       [0.50447066, 0.60522383],
       [0.3617339 , 0.07002045],
       [0.40910776, 0.45906123],
       [0.2650856 , 0.09605274],
       [0.08798813, 0.23981928],
       [0.52931722, 0.34509651],
       [0.56711817, 0.26417791],
       [0.29294614, 0.78465058],
       [0.78453447, 0.26018187]])

In [ ]:
latent_user_preferences

array([[0.58578445, 0.41604012],
       [0.63241519, 0.16854657],
       [0.96459367, 0.59838185],
       ...,
       [0.70566952, 0.16981543],
       [0.81842562, 0.47291063],
       [0.02726734, 0.61434065]])

In [ ]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        #if (iteration % 100) == 0:
        print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
        mse_history.append(mse)
    return mse_history

In [ ]:
#sgd(2)

In [ ]:
num_iter = 20
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
#plt.figure()
#plt.plot(np.arange(0, num_iter, 10), hist)
#plt.xlabel("Iterations")
#plt.ylabel("MSE")
#plt.show()

Iteration 0/20:	MSE=26.205003
Iteration 1/20:	MSE=25.246806
Iteration 2/20:	MSE=24.954144
Iteration 3/20:	MSE=24.718394
Iteration 4/20:	MSE=24.486006
Iteration 5/20:	MSE=24.250867
Iteration 6/20:	MSE=24.013082
Iteration 7/20:	MSE=23.774038
Iteration 8/20:	MSE=23.535439
Iteration 9/20:	MSE=23.299003
Iteration 10/20:	MSE=23.066308
Iteration 11/20:	MSE=22.838671
Iteration 12/20:	MSE=22.617048
Iteration 13/20:	MSE=22.401941
Iteration 14/20:	MSE=22.193308
Iteration 15/20:	MSE=21.990473
Iteration 16/20:	MSE=21.792041
Iteration 17/20:	MSE=21.595817
Iteration 18/20:	MSE=21.398748
Iteration 19/20:	MSE=21.196938

In [ ]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

NameError: ignored

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = test.columns

In [ ]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

                               1    ...                         100
0      (-7.82, 0.6080659580263081)  ...   (nan, 1.1452826538380765)
1       (4.08, 0.9133073408074004)  ...  (1.07, 1.4897541635609177)
2        (nan, 3.5170274944030946)  ...    (nan, 5.311893965097524)
3        (nan, 1.8207374024186462)  ...   (nan, 2.7417453143660078)
4         (8.5, 2.989073993942337)  ...   (1.6, 4.4410220210091005)
...                            ...  ...                         ...
24978   (0.44, 3.0079112196760995)  ...   (7.43, 4.446089758331366)
24979   (9.13, 0.6758235700295671)  ...  (8.45, 0.6811011455467851)
24980   (nan, 0.21333411116688625)  ...   (nan, 0.6266012809672161)
24981    (nan, 1.0717069664388248)  ...    (nan, 1.796357194298205)
24982   (2.43, 2.7212762848924994)  ...   (nan, 3.6285456391261772)

[24983 rows x 100 columns]

In [ ]:
# Load movies data
item_features_df = pd.read_excel('/content/movies_latent_factors.xlsx', sheet_name='Items')
item_features_df.head()

   Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]

In [ ]:
# Load movies data
user_features_df = pd.read_excel('/content/movies_latent_factors.xlsx', sheet_name='Users')
user_features_df.head()

   User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3   174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4  4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669

[5 rows x 16 columns]

In [ ]:
user_features_df.loc[[3], ['Factor15']].head()

   Factor15
3  0.050692

In [ ]:
item_features_df.iloc[df1['Factor6'].idxmin()]

Movie ID                                               672
Title       Harry Potter and the Chamber of Secrets (2002)
Factor1                                            1.30239
Factor2                                           -1.58241
Factor3                                            1.66408
Factor4                                            1.23416
Factor5                                           0.631764
Factor6                                           -2.23746
Factor7                                         -0.0253022
Factor8                                           0.262009
Factor9                                           0.225579
Factor10                                          -2.38033
Factor11                                           2.79234
Factor12                                           2.55065
Factor13                                          0.867521
Factor14                                        -0.0474264
Factor15                                          0.336602
Name: 58, dtype: object

In [ ]:
n_latent_factors = 15

# Initialise as random values
latent_user_preferences = np.random.random((user_features_df.shape[0], n_latent_factors))
latent_item_features = np.random.random((item_features_df.shape[1], n_latent_factors))

In [ ]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

In [ ]:
predict_rating(3, 1)

4.669321783812282

In [ ]:
predict_rating(7, 1)

2.6738451046413094